We need to up our node for node-cache-storage
0.8.15 threw a:

buffer.js:434
      throw new Error('Unknown encoding');
            ^
Error: Unknown encoding
    at Buffer.toString (buffer.js:434:13)
    at Object.fs.readFileSync (fs.js:236:33)
    at FileStorage.getData (/Users/kevin/workspace/on-the-githubs/node_modules/cache-storage/lib/Storage/FileStorage.js:40:32)
    at FileStorage.read (/Users/kevin/workspace/on-the-githubs/node_modules/cache-storage/lib/Storage/FileStorage.js:74:19)
    at Cache.load (/Users/kevin/workspace/on-the-githubs/node_modules/cache-storage/lib/Cache.js:57:27)